### ISSUE TITLE
add riru to layman

### ISSUE THREAD

**Issue by alex-eg** [pkulev/riru#18]
Because why not. I use it actively, and publicity is good anyway!
Let's make ebuilds for all pocket projects and useful stuffs available through official layman. 

It's as simple as filing a bug to Gentoo bugzilla:
https://bugs.gentoo.org/enter_bug.cgi

**Comment by pkulev** [comment]
What we need to do to go public? Some ebuild and overlay metadata QA?

**Comment by alex-eg** [comment]
Official gentoo guide on how to request adding of overlay to layman, and what we should do for this:
[Overlays guide](https://wiki.gentoo.org/wiki/Project:Overlays/Overlays_guide#Requesting_addition_of_new_repositories_.28overlays.29)

**Comment by alex-eg** [comment]
Hey, @pkulev, I think you might find this requirement particularry interesting:

> The repository owner must have a Gentoo Bugzilla account. Bugzilla will be used for all official communications regarding the repository.

**Comment by pkulev** [comment]
https://github.com/gentoo/api-gentoo-org/pull/49
