### ISSUE TITLE
drop www-client/firefox-9999

### ISSUE THREAD

**Issue by okias** [pkulev/riru#49]
Hello @pkulev,

I'm unable to maintain live version and since it's broken, I propose to drop it.

In case you would be interested in maintaining it together with me, we can move to ::mozilla overlay and also be notified of other changes, but right now since it's extreme maintenance burden, not even ::mozilla guys prefer to not maintain -9999 .

**Comment by pkulev** [comment]
Oh, ok.
I personally use firefox-bin, so maybe if @vaartis is not mind we can drop firefox ebuild.

**Comment by vaartis** [comment]
Sure. Drop it. I don't use it any more anyway..
